workspace: true

stages:
  - build
  - nothing
  - test

jobs:
  build:
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la /
      - ls -la /build
      - ps -a
      - ulimit -a
      - sleep 10
      - echo fuck
      - c
    after_script:
      - echo yayfuck
  build2:
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    script:
      - ls -la /

  build3:
    stage: build
    image: sunasteriskrnd/php-workspace:7.4
    services:
      - redis:alpine
    script:
      - echo 'hello'
    artifacts:
      paths:
        - app/
      expires_in: 3 days

  test:
    stage: test
    image: alpine
    script:
      - echo fuck
      - sleep 10
      - echo 'except develop'
    except:
      branches:
        - develop
  test2:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo fuck
    except:
      branches:
        - master
  test3:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo fuck
      - composer install
      - composer sniff
    except:
      branches:
        - develop
